### ISSUE TITLE
Cannot hit /me/ endpoint after obtaining an access token.

### ISSUE THREAD

**Issue by stevenkword** [Automattic/wpcom-connect-examples#1]
{"error":"authorization_required","message":"An active access token must be used to query information about the current user."}

Using the scripts from the PHP example with the define.php values updated for my application.

Ideas?

**Comment by Dielz98** [comment]
So it's not only me!!

I get `access_token`:

```shell
I20160309-23:28:34.432(7)? { access_token: 'fA7zhN8if3sI96C9k)1xKYI6%L97&gPf0uixcgt20D@0zOxkViEPT6WjbM9(^xxx',
I20160309-23:28:34.432(7)?   token_type: 'bearer',
I20160309-23:28:34.432(7)?   blog_id: '59285xxx',
I20160309-23:28:34.432(7)?   blog_url: 'http://xxx.wordpress.com',
I20160309-23:28:34.433(7)?   scope: '' }
```

Using that `access_token` I fail to query information about the current user with `https://public-api.wordpress.com/rest/v1/me/`

After working hours, I found out that wordpress rest deliver invalid token. How do I know? I made token validation:
```css
https://public-api.wordpress.com/oauth2/token-info?client_id=your_client_id&token=your_token
```

It return:
```js
Error in OAuth Server: failed [400] {"error":"invalid_request","error_description":"The specified token is invalid."}
```

This is ridiculous!! This make me believe that wordpress.com won't their user interact with 3rd party app

Please fix this

**Comment by codebykat** [comment]
Hi @Dielz98! I literally just wrote a third-party app using our OAuth code, so I'm pretty convinced it does work. :) Can you share some more details about your implementation? Maybe link to some code?

One thing that sometimes trips people up is that you might need to URI decode/encode the token. Notice that the one you got happens to have an ampersand in it -- that will cause it to truncate the value if you try to just send it as a URL parameter.

Also make double-sure you're passing the same client ID for both requests.

Here's some example code that might help:

https://github.com/codebykat/metonymic/blob/master/amanuensis/js/login.js

You might also try using the v1.1 endpoint instead of v1 and see if that makes any difference. The v1 endpoints are the older version.

**Comment by codebykat** [comment]
Gonna go ahead and close this, please feel free to reopen if you're still having trouble.
